services:
  zap-report:
    image: nginx:alpine
    container_name: zap-report
    ports:
      - "2912:80"
    volumes:
      - ./security-reports:/usr/share/nginx/html:ro
    restart: unless-stopped

