name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 152.42.219.23
          username: root
          key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIABNhG3LfboFw0nlLmuWq1UHvidq6R3yF14m643WRLLb
          port: 2230
          script: |
            set -e
            cd /var/www/projectlabubu
            git pull origin main
            # contoh: kalau Node + PM2
            npm ci --omit=dev || true
            pm2 reload all || pm2 restart all || true
            # kalau cuma static + nginx, cukup git pull saja
            sudo systemctl reload nginx || true
